apiVersion: v1
kind: Service
metadata:
  name: hospital-service
  namespace: hospital
spec:
  selector:
    app: hospital
  type: LoadBalancer
  ports:
  - port: 8080 #service port
    targetPort: 80  #traffic goes inside the container