apiVersion: v1
kind: Secret
metadata: 
  name: hospital-secret
  namespace: hospital

type: Opaque
stringData:
  DB_HOST: mydb.cj44mq6wimjt.ap-southeast-1.rds.amazonaws.com
  DB_USER: admin
  DB_PASSWORD: rpdySN6q|Gcuak3vI1q[OX:<pAzq
  DB_NAME: mydb